# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190812_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, default='N/A', max_length=500, null=True),
        ),
    ]
