# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190813_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
