# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='user',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user-contribution+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
