# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Awaiting pricing'), ('3', 'In development'), ('4', 'Feature added'), ('5', 'Closed')], max_length=1),
        ),
    ]
