# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190712_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='contribution',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='feature',
            name='totalContributions',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
