# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190714_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='totalContributions',
            field=models.IntegerField(),
        ),
    ]
