# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190715_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='totalContributions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
