# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190715_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Awaiting pricing'), ('3', 'In development'), ('4', 'Feature added'), ('5', 'Closed')], default=1, max_length=1),
        ),
    ]
