# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20190715_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='featureName',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
