# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20190715_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_added_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='in_development_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='set_price_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('1', 'Awaiting pricing'), ('2', 'Price set'), ('3', 'In development'), ('4', 'Feature added')], default=1, max_length=1),
        ),
    ]
