# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190723_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='in_development_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='set_price_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
