# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190726_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='totalContributions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
