# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20190807_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
