# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 12:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190712_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Working on it'), ('3', 'Bug resolved')], default=1, max_length=1),
        ),
    ]
