# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190715_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='description',
        ),
    ]
