# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190724_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='views',
            new_name='upvotes',
        ),
    ]
