# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190726_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='devComments',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
