# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0010_auto_20190726_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
